const VALIDATION_TYPE = {
    PHONE_NUMBER: "PHONE_NUMBER",
    EMAIL: "EMAIL",
    USERNAME: "USERNAME",
    COMMUNITY_USERNAME: "COMMUNITY_USERNAME",
    DATE: "DATE",
    NUMBER: "NUMBER",
    ARRAY: "ARRAY",
};
module.exports = { VALIDATION_TYPE };
